// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("trino")
	ScopeName = "github.com/dougkirkley/opentelemetry-collector-trino/exporter/trinoexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
